#!/bin/bash

SCREEN_COUNTER=0
LINE=""
REPLY=""
DIR_PATH="$HOME/Downloads/scalable_display"
WIDTH=0
HEIGHT=0
FILES="$DIRPATH"
BAZEL_SIZE=0
SCREENS_HORIZONTAL=0
SCREENS_VERTICAL=0

echo $FILES

entering()
{
	echo "*********** Entering ${FUNCNAME[1]} **************"
}

exiting()
{
	echo "*********** Exiting ${FUNCNAME[1]} **************"
}

add_width()
{
	echo "Now adding $1's dimensions."
	local TEMP=`head -n 1 "$1"`
	WIDTH=$(( $WIDTH + $TEMP ))
	#WIDTH=$(( $WIDTH+`head -n 1 "$1"` ))
	echo "\$WIDTH = $WIDTH"
}

add_height()
{
	echo "Now adding $1's dimensions."
	local TEMP=`tail -n 1 "$1"`
	HEIGHT=$(( $HEIGHT + $TEMP ))
	#HEIGHT=$HEIGHT+`tail -n 1 "$1"`
	echo "\$HEIGHT = $HEIGHT"
}

check_for_integer()
{
	local TEMP=$1
	echo $TEMP | grep "[^0-9]" > /dev/null 2>&1
	if [ "$?" -eq "0" ]; then
		echo "Please enter a positive integer..."
		eval ${FUNCNAME[1]}
	else
		eval $2=$TEMP
	fi
}

get_num_tiles()
{
	echo -n "Please enter the number of tiles: "
	read 
	check_for_integer $REPLY SCREEN_COUNTER
	echo -n "Please verify that the number of tiles are $SCREEN_COUNTER (yes/no)- "
	read
	REPLY=`echo $REPLY | tr "[:upper:]" "[:lower:]"`
	case $REPLY in
		yes|ye|y)
			echo -n "Please enter number of tiles in horizontal direction- "
			read
			check_for_integer $REPLY SCREENS_HORIZONTAL
			echo -n "Please enter number of tiles in vertical direction- "
			read
			check_for_integer $REPLY SCREENS_VERTICAL
			TEMP=1
			while [ $TEMP -le $SCREENS_HORIZONTAL ]
			do
				#add_dimensions "raspberrypi${TEMP}_screen_resolution.txt"
				add_width "raspberrypi${TEMP}_screen_resolution.txt"
				TEMP=$(( $TEMP + 1 ))
			done

			TEMP=1
			while [ $TEMP -lt $SCREEN_COUNTER ]
			do
				add_height "raspberrypi${TEMP}_screen_resolution.txt"
				TEMP=$(( $TEMP + SCREENS_HORIZONTAL ))
			done
			;;
		no|n)
			get_num_tiles
			;;
		*)
			get_num_tiles
			;;
	esac
}

compensate_bazel()
{
	echo -n "Please enter approximate bazel size to compensate - "
	read
	check_for_integer $REPLY BAZEL_SIZE
}

make_config_file()
{
	local TEMP=0
	local REMAINDER=0 
	local X_COORDS=0
	local Y_COORDS=0
	local BAZEL_WIDTH=$(( WIDTH / SCREENS_HORIZONTAL - BAZEL_SIZE)) # Each tile width
	local BAZEL_HEIGHT=$(( HEIGHT / SCREENS_VERTICAL - BAZEL_SIZE)) # Each tile height

	X_COORDS=0
	Y_COORDS=0

	cat <<-END > .piwall
	[${SCREEN_COUNTER}bez_wall]
	width=$WIDTH
	height=$HEIGHT
	x=0
	y=0


	END

	TEMP=0
	while [ $TEMP -lt $SCREENS_HORIZONTAL ]; do
		cat <<-END >> .piwall	
		[${SCREEN_COUNTER}bez_$(( TEMP + 1 ))]
		wall=${SCREEN_COUNTER}bez_wall
		width=$BAZEL_WIDTH
		height=$BAZEL_HEIGHT
		x=$X_COORDS
		y=$Y_COORDS


		END
	X_COORDS=$(( X_COORDS + BAZEL_WIDTH + BAZEL_SIZE + BAZEL_SIZE ))
	TEMP=$(( $TEMP + 1 ))
	done

	TEMP=$SCREENS_HORIZONTAL
	X_COORDS=0
	Y_COORDS=$(( BAZEL_HEIGHT + BAZEL_SIZE + BAZEL_SIZE + BAZEL_SIZE ))
	while [ $TEMP -lt $SCREEN_COUNTER ]; do
		cat <<-END >> .piwall	
		[${SCREEN_COUNTER}bez_$(( TEMP + 1 ))]
		wall=${SCREEN_COUNTER}bez_wall
		width=$BAZEL_WIDTH
		height=$BAZEL_HEIGHT
		x=$X_COORDS
		y=$Y_COORDS


		END
	X_COORDS=$(( X_COORDS + BAZEL_WIDTH + BAZEL_SIZE))
	TEMP=$(( $TEMP + 1 ))
	done
	
	echo "[${SCREEN_COUNTER}bez]" >> .piwall
	TEMP=0
	while [ $TEMP -lt $SCREEN_COUNTER ]; do
		cat <<-END >> .piwall	
		pi$(( TEMP + 1 ))=${SCREEN_COUNTER}bez_$(( TEMP + 1 ))
		END
	TEMP=$(( TEMP + 1 ))
	done
}

show_file()
{
	echo
	echo "=====================Output of $1==================================="
	cat "$1"
	echo "=====================End of output==================================="
	echo
}

send_config_file()
{
	# Use SCP to transfer to the clients
}



#############################################################################################################
####################################################  MAIN  #################################################
#############################################################################################################

get_num_tiles
echo "Total width = $WIDTH"
echo "Total height = $HEIGHT"
compensate_bazel
make_config_file
show_file ".piwall"
send_config_file
